//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAT602_GUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class player
    {
        public player()
        {
            this.player_game_session = new HashSet<player_game_session>();
            this.player_challenge = new HashSet<player_challenge>();
            this.player_challenge1 = new HashSet<player_challenge>();
        }
    
        public int Player_ID { get; set; }
        public string Player_Name { get; set; }
        public string Player_Password { get; set; }
        public int Player_Login_Attempts { get; set; }
        public bool Player_Locked { get; set; }
    
        public virtual ICollection<player_game_session> player_game_session { get; set; }
        public virtual player_score player_score { get; set; }
        public virtual player_session player_session { get; set; }
        public virtual ICollection<player_challenge> player_challenge { get; set; }
        public virtual ICollection<player_challenge> player_challenge1 { get; set; }
    }
}
