//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAT602_GUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class player_score
    {
        public int Player_ID { get; set; }
        public Nullable<int> Player_Hits { get; set; }
        public Nullable<int> Player_Misses { get; set; }
        public Nullable<int> Player_Wins { get; set; }
        public Nullable<int> Player_Losses { get; set; }
        public Nullable<int> Player_Ties { get; set; }
    
        public virtual player player { get; set; }
    }
}
