//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAT602_GUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class player_challenge
    {
        public int Player1_ID { get; set; }
        public int Player2_ID { get; set; }
        public Nullable<System.DateTime> Challenged_Time { get; set; }
    
        public virtual player player { get; set; }
        public virtual player player1 { get; set; }
    }
}
