//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAT602_EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class npc_game_session
    {
        public int NPC_Game_Session_ID { get; set; }
        public int Game_Session_ID { get; set; }
        public int NPC_ID { get; set; }
        public int NPC_X { get; set; }
        public int NPC_Y { get; set; }
        public int NPC_Z { get; set; }
        public int NPC_TTL { get; set; }
    
        public virtual game_session game_session { get; set; }
        public virtual npc npc { get; set; }
    }
}
