//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAT602_EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class player_session
    {
        public int Player_ID { get; set; }
        public System.DateTime Player_Start_Time { get; set; }
        public Nullable<System.DateTime> Player_End_Time { get; set; }
    
        public virtual player player { get; set; }
    }
}
